### PR TITLE
Update deployOpenShift.sh

### PR DESCRIPTION
**Pull request by Aslamlatheef**

### CODE REVIEW

**Comment by haroldwongms** [comment]
Not sure why you would want to leave installation files behind.  Please help us understand why this is important.  Thanks.

**Comment by Aslamlatheef** [comment]
as you see there are so many deployment failure are currently seen, these files are quite helpful for manual trigger..!! 

later resource can manual delete.

**Comment by haroldwongms** [comment]
The files only get deleted if the deployment is 100% successful.  You want the files left behind and leave it to the admin to manually delete them?

**Comment by Aslamlatheef** [comment]
yes - would help to understand the deployment.

**Comment by BorisB2015** [comment]
@Aslamlatheef - thank you for the suggestion but I'm going to close this without merging. 

Rationale is listed above by @haroldwongms - these files are deleted only if the deployment is 100% successful. Anyone is free to modify the deployment scripts for purposes of understanding (or any other purpose) even for successful deployments in their own repo.

Thanks again!

**Pull request closed without merging**
